# Generated by Django 5.1.6 on 2025-05-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image_car',
            field=models.ImageField(default=None, null=True, upload_to='uploads/'),
        ),
    ]
